Determine the periodic states of the following Markov chain:
```math
\begin{bmatrix}
0 & 0.6 & 0.4 \\
0 & 1 & 0 \\
0.6 & 0.4 & 0
\end{bmatrix}
```

To determine the periodic states in the matrix, let’s examine each state individually for its period by analyzing possible paths from each state back to itself:

```mermaid
graph TD
    A[State 1] -->|0.6| B[State 2]
    A -->|0.4| C[State 3]
    B -->|1| B
    C -->|0.6| A
    C -->|0.4| B
```



#### Checking Each State

1. **State 1**:
   - The probability $P(1 \to 1) = 0$ directly, but we can reach state 1 from state 3, which transitions to state 1 with probability 0.6.
   - Possible paths: $1 \to 3 \to 1$ in two steps.
   - Thus, the period for state 1 is 2, as it returns to itself every 2 steps.

2. **State 2**:
   - $P(2 \to 2) = 1$, meaning it can remain in state 2 indefinitely with no need to transition.
   - This self-loop makes state 2 *aperiodic* (period = 1).

3. **State 3**:
   - $P(3 \to 3) = 0$ directly, but state 3 can return to itself through the path: $3 \to 1 \to 3$, in two steps.
   - Therefore, the period for state 3 is also 2, as it only returns to itself in even steps.

#### Conclusion
The periodic states are:
- **State 1** with period 2
- **State 3** with period 2
  
State 2 is aperiodic (period 1). 

Thus, states 1 and 3 are periodic with period 2, while state 2 is aperiodic. 

In [30]:
import numpy
M = matrix([[0,.6,.4], [0,1,0], [.6, .4, 0]])
M = numpy.ceil(M) 
M 


array([[0., 1., 1.],
       [0., 1., 0.],
       [1., 1., 0.]])

In [31]:
P = Matrix(ZZ, M)
P 

[0 1 1]
[0 1 0]
[1 1 0]

In [32]:
P^2

[1 2 0]
[0 1 0]
[0 2 1]

In [33]:
P^3

[0 3 1]
[0 1 0]
[1 3 0]

In [34]:
P^4 

[1 4 0]
[0 1 0]
[0 4 1]

In [35]:
P^5 

[0 5 1]
[0 1 0]
[1 5 0]